
import Head from 'next/head'
import { BreadcrumbExample } from '@/components/Breadcrumbs';
import { LoanInfo } from './components/LoanInfo';
import { RepaymentSchedule } from './components/RepaymentSchedule';
import { InfoCard } from '@/components/InfoCard';
import { useRouter } from 'next/router';

const loan_id = "LOANICIABC12345"

const arr_data = [
    { title: "Total Amount Disbured", amount: "USD 20,000"},
    { title: "Outstanding Prinicipal", amount: "USD 7,000"},
    { title: "Ongoing EMI", amount: "USD 500"},
    { title: "Remaining EMIs", amount: "40 Months"},
    
]

export default function ApplyLoan() {

    const router = useRouter();
    const offer_id = router?.query?.id?.toString();
  return (
    <>
        <Head>
            <title>Loan ID : {loan_id}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <BreadcrumbExample 
            data={[{
                title: "My Loans",
                link: "/my-loans"
            }]}
            active={loan_id}
        />
        <main id="main-div">
            <InfoCard 
                data={arr_data}
            />
            <br />
            <LoanInfo />
            <hr />
            <RepaymentSchedule />
        </main>
    </>
  )
}
