
import Head from 'next/head'
import { BreadcrumbExample } from '@/components/Breadcrumbs';
import LenderLoanTable from './components/LenderLoanTable';
import { InfoCard } from '@/components/InfoCard';

const arr_data = [
  { title: "Outstanding Principal Balance", amount: "USD 120,000"},
  { title: "Total Ongoing EMI", amount: "USD 3,000"},
  { title: "Ongoing Loans", amount: "3"},
  { title: "Total Amount Disbursed", amount: "200,000"},
  { title: "Total Loan Requests Pending", amount: "4"},
  { title: "Total Loans Cleared", amount: "6"},
  { title: "Total Rejected Loans", amount: "6"},
]

export default function LenderLoans() {
  return (
    <>
        <Head>
            <title>Lender Loans</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <BreadcrumbExample 
          data={[]}
          active={"Lender Loans"}
        />
        <main id="main-div">
            <div className="main-box p-3">
            <InfoCard
              data = {arr_data}
            />
            <br />
            <LenderLoanTable />
            </div>
        </main>
    </>
  )
}
