import Head from 'next/head'
import OfferTable from './components/OfferTable';
import { BreadcrumbExample } from '@/components/Breadcrumbs';
import { Filters } from './components/Filters';
import NotificationsDropdown from '@/components/NotificationsDropdown';



export default function Offers() {
  return (
    <>
        <BreadcrumbExample 
          data={[]}
          active={"Offers"}
        />
        <Head>
            <title>Loan Offers</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main id="main-div">
            <div className="main-box">
              <Filters />
              <OfferTable />
            </div>
            <NotificationsDropdown />
        </main>
    </>
  )
}
