
import Head from 'next/head'
import { BreadcrumbExample } from '@/components/Breadcrumbs';
import { InfoCard } from '@/components/InfoCard';
import MyLoansTable from './components/MyLoanTable';

const loan_id = "LOANICIABC12345"

const arr_data = [
    { title: "Total Assets Sold", amount: "5"},
    { title: "Asset Cost", amount: "USD 200,000"},
]

export default function ApplyLoan() {

    
    return (
    <>
        <Head>
            <title>Loan ID : {loan_id}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <BreadcrumbExample 
            data={[]}
            active={"Asset Onwer"}
        />
        <main id="main-div">
            <InfoCard 
                data={arr_data}
            />
            <br />
            <MyLoansTable />
        </main>
    </>
  )
}
